LIST 	P=PIC16F877
#include <P16f877.inc>

LCD CODE 0x91

INITDisplay:
   
   ;CALL BANK1 
   BANKSEL TRISD                  
   CLRF TRISD                  
   MOVLW 0X06                  
   MOVWF ADCON1                ;SET ALL TO D
   CLRF TRISE
   ;CALL BANK0
   BANKSEL PORTD
   MOVLW 0X30                  ;RESET SCREEN
   MOVWF PORTD
   CALL FUNCTION.LCD.WRITE
   CALL INITDELAY
   MOVLW 0X30
   MOVWF PORTD
   CALL FUNCTION.LCD.WRITE
   CALL INITDELAY
   MOVLW 0X30
   MOVWF PORTD
   CALL FUNCTION.LCD.WRITE
   CALL INITDELAY              ;END SCREEN RESET
   MOVLW 0X38                  ;SET CONFIG. FOR SCREEN
   MOVWF PORTD
   CALL FUNCTION.LCD.WRITE
   MOVLW 0X0C                  ;DISPLAY=ON BIT.D=1
   MOVWF PORTD                 
   CALL FUNCTION.LCD.WRITE
   MOVLW 0X01                  ;DISPLAY CLEAR
   MOVWF PORTD
   CALL FUNCTION.LCD.WRITE 
   MOVLW 0X06                  ;DISPLAY SET L.T.R
   MOVWF PORTD
   CALL FUNCTION.LCD.WRITE
   
   RETURN

 GLOBAL INITDisplay
   
FUNCTION.LCD.WRITE:            ;FUNCTION WRITE TO LCD

 BCF PORTE,RE1
 BSF PORTE,RE0
 CALL INITDELAY
 BCF PORTE,RE0
    
    RETURN

 
    
VAL.LCD.WRITE:                 ;VAL WRITE ON SCREEN

 BSF PORTE,RE1
 BSF PORTE,RE0
 CALL INITDELAY
 BCF PORTE,RE0
    
   RETURN    

PRINT.SEC:
    
    
PRINT.MIN:
    
PRINT.HOUR:    
    
PRINT.255:
        
   MOVLW 0X86
   MOVWF PORTD
   
   CALL FUNCTION.LCD.WRITE
   CALL ASCII.NUMBER
   
   MOVLW 0X03
   MOVWF 0X48
   
   MOVLW 0X52
   MOVWF FSR
   
LOOP.3:   
   
   MOVFW INDF
   MOVWF PORTD
   CALL VAL.LCD.WRITE
   DECF FSR,F
   DECFSZ 0X48,F
   GOTO LOOP.3
   
   RETURN   

 GLOBAL PRINT.255   

ASCII.NUMBER:
   
   MOVLW 0X03
   MOVWF 0X48
   
   MOVLW 0X52
   MOVWF FSR
   
   MOVLW 0X30
   
LOOP.ASCII:
   
   ADDWF INDF,F    
   DECF FSR,F
   DECFSZ 0X48,F
   GOTO LOOP.ASCII
   
   RETURN

 FORMAT.TIME:
          
   MOVLW 0X84
   MOVWF PORTD
   CALL FUNCTION.LCD.WRITE 
   
   MOVLW 0x48
   MOVWF PORTD
   CALL VAL.LCD.WRITE
   CALL VAL.LCD.WRITE
   
   MOVLW 0x3A
   MOVWF PORTD
   CALL VAL.LCD.WRITE
   
   MOVLW 0x4D
   MOVWF PORTD
   CALL VAL.LCD.WRITE
   CALL VAL.LCD.WRITE
   
   MOVLW 0x3A
   MOVWF PORTD
   CALL VAL.LCD.WRITE
   
   MOVLW 0x53
   MOVWF PORTD
   CALL VAL.LCD.WRITE
   CALL VAL.LCD.WRITE

   MOVLW 0xC4
   MOVWF PORTD
   CALL FUNCTION.LCD.WRITE

   MOVLW 0x53
   MOVWF PORTD
   CALL VAL.LCD.WRITE
   CALL VAL.LCD.WRITE

   MOVLW 0x3A
   MOVWF PORTD
   CALL VAL.LCD.WRITE
   
   MOVLW 0x53
   MOVWF PORTD
   CALL VAL.LCD.WRITE
   CALL VAL.LCD.WRITE

   MOVLW 0x3A
   MOVWF PORTD
   CALL VAL.LCD.WRITE

   MOVLW 0x53
   MOVWF PORTD
   CALL VAL.LCD.WRITE
   CALL VAL.LCD.WRITE

   RETURN
GLOBAL FORMAT.TIME   
   
BANK0:

    BCF STATUS,IRP
    BCF STATUS,RP0
    BCF STATUS,RP1
    
    RETURN
    
BANK1:

    BCF STATUS,IRP
    BCF STATUS,RP1
    BSF STATUS,RP0
    
    RETURN
    
BANK2:

    BSF STATUS,IRP
    BSF STATUS,RP1
    BCF STATUS,RP0
    
    RETURN 
    
BANK3:

    BSF STATUS,IRP
    BSF STATUS,RP1
    BSF STATUS,RP0
    
    RETURN   

INITDELAY:          ;INIT DELAY 2ms

    movlw 0X20          
    movwf 0x40         
    
DELAY0:
    
    DECFSZ 0x40,f
    GOTO DELAY0
    
    RETURN
        
    END