   LIST P=PIC16F877
#include <P16f877.inc>

LCD CODE 0x9F
INITDisplay:
   
   ;CALL BANK1 
   BANKSEL TRISD                  
   CLRF TRISD                  
   MOVLW 0X06                  
   MOVWF ADCON1                ;SET ALL TO D
   CLRF TRISE
   ;CALL BANK0
   BANKSEL PORTD
   MOVLW 0X30                  ;RESET SCREEN
   
   CALL FUNCTION.LCD.WRITE
   CALL INITDELAY
   MOVLW 0X30
   
   CALL FUNCTION.LCD.WRITE
   CALL INITDELAY
   MOVLW 0X30
   
   CALL FUNCTION.LCD.WRITE
   CALL INITDELAY              ;END SCREEN RESET
   MOVLW 0X38                  ;SET CONFIG. FOR SCREEN
   
   CALL FUNCTION.LCD.WRITE
   MOVLW 0X0C                  ;DISPLAY=ON BIT.D=1
                    
   CALL FUNCTION.LCD.WRITE
   MOVLW 0X01                  ;DISPLAY CLEAR
   
   CALL FUNCTION.LCD.WRITE 
   MOVLW 0X06                  ;DISPLAY SET L.T.R
   
   CALL FUNCTION.LCD.WRITE
   
   RETURN

 GLOBAL INITDisplay
   
FUNCTION.LCD.WRITE:            ;FUNCTION WRITE TO LCD

 MOVWF PORTD   
 BCF PORTE,RE1
 BSF PORTE,RE0
 CALL INITDELAY
 BCF PORTE,RE0
    
    RETURN

 
    
VAL.LCD.WRITE:                 ;VAL WRITE ON SCREEN

 MOVWF PORTD   
 BSF PORTE,RE1
 BSF PORTE,RE0
 CALL INITDELAY
 BCF PORTE,RE0
    
   RETURN    

;-----------------255.function------------------------------;   
PRINT.255:
        
   MOVLW 0X86
   CALL FUNCTION.LCD.WRITE
   CALL ASCII.NUMBER.255
   
   MOVLW 0X03
   MOVWF 0X48
   
   MOVLW 0X52
   MOVWF FSR
   
LOOP.3:   
   
   MOVFW INDF
   
   CALL VAL.LCD.WRITE
   DECF FSR,F
   DECFSZ 0X48,F
   GOTO LOOP.3
   
   RETURN   

 GLOBAL PRINT.255   

ASCII.NUMBER.255:
   
   MOVLW 0X03
   MOVWF 0X48
   
   MOVLW 0X52
   MOVWF FSR
   
   MOVLW 0X30
   
LOOP.ASCII.255:
   
   ADDWF INDF,F    
   DECF FSR,F
   DECFSZ 0X48,F
   GOTO LOOP.ASCII.255
   
   RETURN
;-----------------TIME.FUNCTION-------------------------------;
FORMAT.TIME:
          
   MOVLW 0X84
   CALL FUNCTION.LCD.WRITE 
   
   MOVLW 0x48
   CALL VAL.LCD.WRITE
   MOVLW 0x48
   CALL VAL.LCD.WRITE
   
   MOVLW 0x3A
   CALL VAL.LCD.WRITE
   
   MOVLW 0x4D
   CALL VAL.LCD.WRITE
    MOVLW 0x4D
   CALL VAL.LCD.WRITE
   
   MOVLW 0x3A
   CALL VAL.LCD.WRITE
   
   MOVLW 0x53
   CALL VAL.LCD.WRITE
   MOVLW 0x53
   CALL VAL.LCD.WRITE

   MOVLW 0xC4
   CALL FUNCTION.LCD.WRITE

   MOVLW 0x30
   CALL VAL.LCD.WRITE
   MOVLW 0x30
   CALL VAL.LCD.WRITE

   MOVLW 0x3A
   CALL VAL.LCD.WRITE
   
   MOVLW 0x30
   CALL VAL.LCD.WRITE
   MOVLW 0x30
   CALL VAL.LCD.WRITE

   MOVLW 0x3A
   CALL VAL.LCD.WRITE

   MOVLW 0x30
   CALL VAL.LCD.WRITE
   MOVLW 0x30
   CALL VAL.LCD.WRITE
   
   RETURN

   GLOBAL FORMAT.TIME   
   
PRINT.TIME:
    
    CALL FUNCTION.LCD.WRITE
    CALL ASCII.NUMBER.TIME
    
    MOVLW 0X02
    MOVWF 0X48
    
    MOVLW 0X51
    MOVWF FSR
    
LOOP.TIME.2:
    
    MOVFW INDF
    CALL VAL.LCD.WRITE
    
    DECF FSR,1
    DECFSZ 0X48,F
    GOTO LOOP.TIME.2
    
    RETURN

    GLOBAL PRINT.TIME
    
ASCII.NUMBER.TIME:
   
   MOVLW 0X02
   MOVWF 0X48
   
   MOVLW 0X50
   MOVWF FSR
   
   MOVLW 0X30
   
LOOP.ASCII.TIME:
   
   ADDWF INDF,F    
   INCF FSR,F
   DECFSZ 0X48,F
   GOTO LOOP.ASCII.TIME
   
   RETURN



BANK0:

    BCF STATUS,IRP
    BCF STATUS,RP0
    BCF STATUS,RP1
    
    RETURN
    
BANK1:

    BCF STATUS,IRP
    BCF STATUS,RP1
    BSF STATUS,RP0
    
    RETURN
    
BANK2:

    BSF STATUS,IRP
    BSF STATUS,RP1
    BCF STATUS,RP0
    
    RETURN 
    
BANK3:

    BSF STATUS,IRP
    BSF STATUS,RP1
    BSF STATUS,RP0
    
    RETURN   

INITDELAY:          ;INIT DELAY 2ms

    movlw 0X20          
    movwf 0x40         
    
DELAY0:
    
    DECFSZ 0x40,f
    GOTO DELAY0
    
    RETURN
        
    END